### ISSUE TITLE
running "bazel build //cc/google/fhir_examples:ParsePatients" on Ubuntu creates errors

### ISSUE THREAD

**Issue by KiwiFPVHarry** [google/fhir-examples#9]
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository fhir_bazel_pip_dependencies instantiated at:
  /home/h/fhir-examples/WORKSPACE:23:12: in <toplevel>
  /home/h/.cache/bazel/_bazel_h/53cd8c1ffe775ea94a7e4204fd2a4fc0/external/rules_python/python/pip.bzl:128:15: in pip3_import
Repository rule pip_import defined at:
  /home/h/.cache/bazel/_bazel_h/53cd8c1ffe775ea94a7e4204fd2a4fc0/external/rules_python/python/pip.bzl:51:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'fhir_bazel_pip_dependencies':
   Traceback (most recent call last):
	File "/home/h/.cache/bazel/_bazel_h/53cd8c1ffe775ea94a7e4204fd2a4fc0/external/rules_python/python/pip.bzl", line 49, column 13, in _pip_import_impl
		fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/h/.cache/bazel/_bazel_h/53cd8c1ffe775ea94a7e4204fd2a4fc0/external/rules_python/tools/piptool.par/__main__.py", line 71, in <module>
  File "/tmp/tmpusr4m7d_/pip-tmp/pip/__init__.py", line 43, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/tmp/tmpusr4m7d_/pip-tmp/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/tmp/tmpusr4m7d_/pip-tmp/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
)
ERROR: no such package '@fhir_bazel_pip_dependencies//': pip_import failed:  (Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/h/.cache/bazel/_bazel_h/53cd8c1ffe775ea94a7e4204fd2a4fc0/external/rules_python/tools/piptool.par/__main__.py", line 71, in <module>
  File "/tmp/tmpusr4m7d_/pip-tmp/pip/__init__.py", line 43, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/tmp/tmpusr4m7d_/pip-tmp/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/tmp/tmpusr4m7d_/pip-tmp/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
)

**Comment by KiwiFPVHarry** [comment]
Python is version 3.8.6, Bazel is verison 3.7.0, Java 11.0.9, Ubuntu 20.10 64 bit.

**Comment by Cam2337** [comment]
Hi @KiwiFPVHarry!

Could you confirm whether there's a `pip` binary installed for your Python interpreter?
```
python3 --version
python3 -m pip
```

The [Bazel workspace](https://github.com/google/fhir-examples/blob/master/WORKSPACE) installs pip requirements during setup, and in doing so will require `pip` to be discoverable on your `PATH`. Even if you're trying to build for a target in `//cc/...` you'll need to have an environment that supports the workspace setup.

Based on the error message you may need to install `python3-distutils` it seems? I'd be curious to see if:
```
apt list | grep -i distutils
```

shows anything?

**Comment by Cam2337** [comment]
We'll look at to see if there's any way we can split this more cleanly too -- as for someone _just_ interested in `//cc/...`, it seems unnecessary to also provision Python, go, ..., etc.

**Comment by KiwiFPVHarry** [comment]
after installing pip it has now completed only to get the next error when tryignt o run bazel-bin

bazel build //cc/google/fhir_examples:ParsePatients
Starting local Bazel server and connecting to it...
INFO: Analyzed target //cc/google/fhir_examples:ParsePatients (60 packages loaded, 2452 targets configured).
INFO: Found 1 target...
Target //cc/google/fhir_examples:ParsePatients up-to-date:
  bazel-bin/cc/google/fhir_examples/ParsePatients
INFO: Elapsed time: 19.726s, Critical Path: 2.24s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
h@h-virtual-machine:~/fhir-examples$ bazel-bin/cc/google/fhir_examples:ParsePatient $WORKSPACE
bash: bazel-bin/cc/google/fhir_examples:ParsePatient: No such file or directory

**Comment by Cam2337** [comment]
> h@h-virtual-machine:~/fhir-examples$ bazel-bin/cc/google/fhir_examples:ParsePatient $WORKSPACE
> bash: bazel-bin/cc/google/fhir_examples:ParsePatient: No such file or directory

Ah I see -- this looks to be an error in the `README.md` which I've since corrected internally. The corrected documentation will be included in the next push to the public repo.

Try running:
```
bazel-bin/cc/google/fhir_examples/ParsePatients $WORKSPACE
```

Which is just a relative path to the compiled binary created from the `bazel` target: `//cc/google/fhir_examples:ParsePatients`.

Let me know if that ends up fixing things for you!

**Comment by KiwiFPVHarry** [comment]
Thank you  - running now..should taht take quite some time? running on a Ubuntu VM inside of WIndows

**Comment by Cam2337** [comment]
It shouldn't be considerably long, maybe a minute or so, to parse all 1000 records. It should be dumping to `STDOUT` as well as it's making progress. What are you seeing?

**Comment by KiwiFPVHarry** [comment]
Reading /home/h/fhirdata and blinking cursor...for about 10 minutes already

**Comment by KiwiFPVHarry** [comment]
did just run it again...cursor stops blinking after a few seconds

**Comment by Cam2337** [comment]
Yeah something's not right. I'm guessing that the `generate_synthea.sh` script didn't execute properly, and that you have no files in `$WORKSPACE/ndjson`. Could you verify if this is true?
```
ls $WORKSPACE/ndjson/
```

**Comment by KiwiFPVHarry** [comment]
all good now..have re-run the synthea script after deleting all but top folder and then all the commands executed successfully..:) thnaks for all the help..:)

**Comment by Cam2337** [comment]
Glad to hear it! :)

To add some additional context for what you might have encountered -- unfortunately the `generate_synthea.sh` script can fail certain steps but continue execution and _appear_ as though it succeeded. I noticed, for example, on one Ubuntu VM, that since I didn't have a `bazel` alias (the correct invocation was `bazel-3.2.0`), the `bazel build @com_google_fhir//java:SplitBundle` command would fail but the rest of the script would continue. This resulted in no files output to `$WORKSPACE/ndjson`.

Because of this, when we eventually would try to execute the compiled `ParsePatients` binary, we were actually spinning indefinitely within the `while` loop as [no data was ever read](https://github.com/google/fhir-examples/blob/master/cc/google/fhir_examples/parse_patients.cc#L57), since no files existed within `$WORKSPACE/ndjson` to begin with. Hence the hanging cursor you were seeing after `Reading <workspace>` was printed to STDOUT.

I've added additional safety to `parse_patients.cc` so that it will error and exit clearly if these problems occur. I'll also look into adding some additional safety to `generate_synthea.sh`.

Glad things are working, thanks for your help and patience! :)
